# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AccessibilityChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for AccessibilityChat
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'SwiftLint'
  pod 'Cartography'
  pod 'SwiftMaskTextfield'
  pod 'IQKeyboardManagerSwift'
  pod 'Gifu', '~> 3.2'
end
